version: "3"
services:
  server:
    image: hospital
    ports:
      - "8080:8080"
    environment:
      - spring.datasource.url=jdbc:mysql://mysqldb:3306/hospital
    networks:
      - springmysql-net
    depends_on:
      - mysqldb

  mysqldb:
    image: mysql:8.0
    networks:
      - springmysql-net
    environment:
      - MYSQL_ROOT_PASSWORD=test
      - MYSQL_DATABASE=hospital
      - MYSQL_USER=notroot
      - MYSQL_PASSWORD=test

networks:
  springmysql-net: